# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\CLONE\QC-Formula/Init_Window_v104.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 460))
        MainWindow.setMaximumSize(QtCore.QSize(650, 460))
        MainWindow.setWindowOpacity(1.25)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TopTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TopTabWidget.setGeometry(QtCore.QRect(25, 15, 600, 200))
        self.TopTabWidget.setTabBarAutoHide(False)
        self.TopTabWidget.setObjectName("TopTabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.DOCPage_LoadButton = QtWidgets.QPushButton(self.tab_2)
        self.DOCPage_LoadButton.setGeometry(QtCore.QRect(470, 25, 100, 32))
        self.DOCPage_LoadButton.setObjectName("DOCPage_LoadButton")
        self.DOCPage_InfoButton = QtWidgets.QPushButton(self.tab_2)
        self.DOCPage_InfoButton.setGeometry(QtCore.QRect(470, 55, 100, 32))
        self.DOCPage_InfoButton.setObjectName("DOCPage_InfoButton")
        self.DOCPage_ConfirmButton = QtWidgets.QPushButton(self.tab_2)
        self.DOCPage_ConfirmButton.setGeometry(QtCore.QRect(470, 125, 100, 32))
        self.DOCPage_ConfirmButton.setObjectName("DOCPage_ConfirmButton")
        self.DOCPage_ImageLabel = QtWidgets.QLabel(self.tab_2)
        self.DOCPage_ImageLabel.setGeometry(QtCore.QRect(45, 39, 380, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DOCPage_ImageLabel.setFont(font)
        self.DOCPage_ImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.DOCPage_ImageLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DOCPage_ImageLabel.setLineWidth(1)
        self.DOCPage_ImageLabel.setMidLineWidth(1)
        self.DOCPage_ImageLabel.setScaledContents(False)
        self.DOCPage_ImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCPage_ImageLabel.setObjectName("DOCPage_ImageLabel")
        self.DOCPage_LoadButton_clipboard = QtWidgets.QPushButton(self.tab_2)
        self.DOCPage_LoadButton_clipboard.setGeometry(QtCore.QRect(470, 90, 100, 32))
        self.DOCPage_LoadButton_clipboard.setObjectName("DOCPage_LoadButton_clipboard")
        self.TopTabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.URLPage_label_1 = QtWidgets.QLabel(self.tab)
        self.URLPage_label_1.setGeometry(QtCore.QRect(10, 5, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.URLPage_label_1.setFont(font)
        self.URLPage_label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.URLPage_label_1.setObjectName("URLPage_label_1")
        self.URLPage_ConfirmButton = QtWidgets.QPushButton(self.tab)
        self.URLPage_ConfirmButton.setEnabled(False)
        self.URLPage_ConfirmButton.setGeometry(QtCore.QRect(470, 125, 100, 32))
        self.URLPage_ConfirmButton.setObjectName("URLPage_ConfirmButton")
        self.URL_Filler = QtWidgets.QLineEdit(self.tab)
        self.URL_Filler.setGeometry(QtCore.QRect(100, 10, 341, 21))
        self.URL_Filler.setAcceptDrops(False)
        self.URL_Filler.setFrame(True)
        self.URL_Filler.setReadOnly(False)
        self.URL_Filler.setClearButtonEnabled(True)
        self.URL_Filler.setObjectName("URL_Filler")
        self.URLPage_LoadButton = QtWidgets.QPushButton(self.tab)
        self.URLPage_LoadButton.setEnabled(False)
        self.URLPage_LoadButton.setGeometry(QtCore.QRect(470, 5, 100, 32))
        self.URLPage_LoadButton.setObjectName("URLPage_LoadButton")
        self.DOCPage_ImageLabel_2 = QtWidgets.QLabel(self.tab)
        self.DOCPage_ImageLabel_2.setGeometry(QtCore.QRect(45, 50, 380, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DOCPage_ImageLabel_2.setFont(font)
        self.DOCPage_ImageLabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.DOCPage_ImageLabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DOCPage_ImageLabel_2.setLineWidth(1)
        self.DOCPage_ImageLabel_2.setMidLineWidth(1)
        self.DOCPage_ImageLabel_2.setScaledContents(False)
        self.DOCPage_ImageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCPage_ImageLabel_2.setObjectName("DOCPage_ImageLabel_2")
        self.TopTabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Setting_Label_1 = QtWidgets.QLabel(self.tab_3)
        self.Setting_Label_1.setGeometry(QtCore.QRect(25, 10, 241, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Setting_Label_1.setFont(font)
        self.Setting_Label_1.setObjectName("Setting_Label_1")
        self.Setting_Label_2 = QtWidgets.QLabel(self.tab_3)
        self.Setting_Label_2.setGeometry(QtCore.QRect(25, 35, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Setting_Label_2.setFont(font)
        self.Setting_Label_2.setObjectName("Setting_Label_2")
        self.Setting_Label_3 = QtWidgets.QLabel(self.tab_3)
        self.Setting_Label_3.setGeometry(QtCore.QRect(25, 65, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Setting_Label_3.setFont(font)
        self.Setting_Label_3.setObjectName("Setting_Label_3")
        self.Setting_Label_4 = QtWidgets.QLabel(self.tab_3)
        self.Setting_Label_4.setGeometry(QtCore.QRect(25, 95, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Setting_Label_4.setFont(font)
        self.Setting_Label_4.setObjectName("Setting_Label_4")
        self.Input_APPID = QtWidgets.QLineEdit(self.tab_3)
        self.Input_APPID.setGeometry(QtCore.QRect(130, 40, 301, 21))
        self.Input_APPID.setObjectName("Input_APPID")
        self.Input_APISecret = QtWidgets.QLineEdit(self.tab_3)
        self.Input_APISecret.setGeometry(QtCore.QRect(130, 70, 301, 21))
        self.Input_APISecret.setObjectName("Input_APISecret")
        self.Input_APIKey = QtWidgets.QLineEdit(self.tab_3)
        self.Input_APIKey.setGeometry(QtCore.QRect(130, 100, 301, 21))
        self.Input_APIKey.setObjectName("Input_APIKey")
        self.Setting_ConfirmButton = QtWidgets.QPushButton(self.tab_3)
        self.Setting_ConfirmButton.setGeometry(QtCore.QRect(470, 125, 100, 32))
        self.Setting_ConfirmButton.setObjectName("Setting_ConfirmButton")
        self.Setting_HelpButton = QtWidgets.QPushButton(self.tab_3)
        self.Setting_HelpButton.setGeometry(QtCore.QRect(470, 95, 100, 32))
        self.Setting_HelpButton.setObjectName("Setting_HelpButton")
        self.Setting_WebsiteButton = QtWidgets.QPushButton(self.tab_3)
        self.Setting_WebsiteButton.setGeometry(QtCore.QRect(470, 25, 100, 32))
        self.Setting_WebsiteButton.setObjectName("Setting_WebsiteButton")
        self.TopTabWidget.addTab(self.tab_3, "")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(25, 260, 600, 155))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Setting_Label_5 = QtWidgets.QLabel(self.centralwidget)
        self.Setting_Label_5.setGeometry(QtCore.QRect(30, 227, 281, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Setting_Label_5.setFont(font)
        self.Setting_Label_5.setObjectName("Setting_Label_5")
        self.Setting_CopyButton = QtWidgets.QPushButton(self.centralwidget)
        self.Setting_CopyButton.setGeometry(QtCore.QRect(500, 225, 100, 32))
        self.Setting_CopyButton.setObjectName("Setting_CopyButton")
        self.Copy_Status_Label = QtWidgets.QLabel(self.centralwidget)
        self.Copy_Status_Label.setGeometry(QtCore.QRect(340, 227, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Copy_Status_Label.setFont(font)
        self.Copy_Status_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Copy_Status_Label.setObjectName("Copy_Status_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionAPI = QtWidgets.QAction(MainWindow)
        self.actionAPI.setObjectName("actionAPI")
        self.action_GiteeTutorial = QtWidgets.QAction(MainWindow)
        self.action_GiteeTutorial.setObjectName("action_GiteeTutorial")
        self.action_GithubTutorial = QtWidgets.QAction(MainWindow)
        self.action_GithubTutorial.setObjectName("action_GithubTutorial")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.menu.addAction(self.action_GiteeTutorial)
        self.menu.addAction(self.action_GithubTutorial)
        self.menu.addSeparator()
        self.menu.addAction(self.action_About)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.TopTabWidget.setCurrentIndex(0)
        self.DOCPage_LoadButton.clicked.connect(MainWindow.img_Load_From_Doc)
        self.DOCPage_LoadButton.clicked.connect(MainWindow.img_Display_In_Doc_Label)
        self.Setting_ConfirmButton.clicked.connect(MainWindow.Setting_API_Values)
        self.DOCPage_InfoButton.clicked.connect(MainWindow.Get_img_Info)
        self.Setting_CopyButton.clicked.connect(MainWindow.Copy_Formula_Result)
        self.DOCPage_ConfirmButton.clicked.connect(MainWindow.Formula_OCR_Execute_iFLY)
        self.Setting_HelpButton.clicked.connect(MainWindow.Get_API_Tutorial)
        self.Setting_WebsiteButton.clicked.connect(MainWindow.Link_To_Official_Site)
        self.action_GiteeTutorial.triggered.connect(MainWindow.Link_To_Gitee_Tutorial)
        self.action_GithubTutorial.triggered.connect(MainWindow.Link_To_Github_Tutorial)
        self.action_About.triggered.connect(MainWindow.About_Software)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QingChen Formula - 青尘公式 OCR"))
        self.DOCPage_LoadButton.setText(_translate("MainWindow", "选择图片..."))
        self.DOCPage_InfoButton.setText(_translate("MainWindow", "图片信息"))
        self.DOCPage_ConfirmButton.setText(_translate("MainWindow", "识别公式"))
        self.DOCPage_ImageLabel.setText(_translate("MainWindow", "公式预览"))
        self.DOCPage_LoadButton_clipboard.setText(_translate("MainWindow", "读取粘贴板"))
        self.TopTabWidget.setTabText(self.TopTabWidget.indexOf(self.tab_2), _translate("MainWindow", "从文件导入"))
        self.URLPage_label_1.setText(_translate("MainWindow", "图片网址："))
        self.URLPage_ConfirmButton.setText(_translate("MainWindow", "识别公式"))
        self.URLPage_LoadButton.setText(_translate("MainWindow", "载入图片"))
        self.DOCPage_ImageLabel_2.setText(_translate("MainWindow", "URL 导入功能开发中...\n"
"\n"
"可访问青尘工作室官网：\n"
"https://qingchen1995.gitee.io 了解开发进度"))
        self.TopTabWidget.setTabText(self.TopTabWidget.indexOf(self.tab), _translate("MainWindow", "从 URL 导入"))
        self.Setting_Label_1.setText(_translate("MainWindow", "公式识别 API 设置"))
        self.Setting_Label_2.setText(_translate("MainWindow", "APPID:"))
        self.Setting_Label_3.setText(_translate("MainWindow", "APISecret:"))
        self.Setting_Label_4.setText(_translate("MainWindow", "APIKey:"))
        self.Setting_ConfirmButton.setText(_translate("MainWindow", "确定"))
        self.Setting_HelpButton.setText(_translate("MainWindow", "获取 API"))
        self.Setting_WebsiteButton.setText(_translate("MainWindow", "访问官网"))
        self.TopTabWidget.setTabText(self.TopTabWidget.indexOf(self.tab_3), _translate("MainWindow", "公式识别设置"))
        self.Setting_Label_5.setText(_translate("MainWindow", "公式识别结果 (LaTeX 格式)："))
        self.Setting_CopyButton.setText(_translate("MainWindow", "复制文本"))
        self.Copy_Status_Label.setText(_translate("MainWindow", "复制完成！"))
        self.menu.setTitle(_translate("MainWindow", "帮助菜单"))
        self.actionAPI.setText(_translate("MainWindow", "API"))
        self.action_GiteeTutorial.setText(_translate("MainWindow", "从码云查看教程"))
        self.action_GiteeTutorial.setToolTip(_translate("MainWindow", "从码云查看教程"))
        self.action_GithubTutorial.setText(_translate("MainWindow", "从 Github 查看教程"))
        self.action_About.setText(_translate("MainWindow", "关于..."))

